### ISSUE TITLE
Plugin breaks svg uploads

### ISSUE THREAD

**Issue by ShallowRed** [felixhaeberle/kirby3-webp#10]
Hi, when using this plugin i cannot upload svg files anymore from the panel, as they trigger the `file.create:after` hook but can't be converted to webp. (actually they get uploaded but trigger an error message).

I think `.svg` extension should be detected and ignored. To do so I replaced plugin's `index.php` with:

```php
<?php

@include_once __DIR__ . '/vendor/autoload.php';
@include_once __DIR__ . '/src/webp.php';

Kirby::plugin('felixhaeberle/kirby3-webp', [
    'hooks' => [
        'file.create:after' => function ($file) {
			if ($this->option('kirby3-webp', false) && $file->extension() !== 'svg') {
                (new WebP\Convert)->generateWebP($file);
            }
        },
        'file.replace:after' => function ($newFile, $oldFile) {
			if ($this->option('kirby3-webp', false) && $file->extension() !== 'svg') {
                (new WebP\Convert)->generateWebP($newFile);
            }
        },
    ],
]);
```

Thanks for the plugin and cheers !

**Comment by jasminsallam** [comment]
Hey! I also noticed that issue when uploading WebP files. those should also be detected and ignored. 

thanks!

**Comment by felixhaeberle** [comment]
#13 fixes this.
