### ISSUE TITLE
Support srcset / hook into file->srcset?

### ISSUE THREAD

**Issue by rcvd** [felixhaeberle/kirby3-webp#3]
I'm using srcsets (different sized versions for different devices) for all of my images with a custom kirbytag which calls $file->srcset. The srcsets are created at first request. As far as I can see, your plugin does not support creating webp files for this yet. Is it possible to implement a hook like this?

**Comment by felixhaeberle** [comment]
Yeah, this sounds like a good idea! Do you want to share a implementation suggestion in a pull request? Very appreciated 🤙

**Comment by vitali-sigel** [comment]
👋  hey, i don't have a implementation suggestion but i also would love to see srcset support for webp.

**Comment by psntr** [comment]
So this plugin convert the original image only? Meaning if the original JPG/PNG is 2592x1900, and we use this in the frontend, it will output a 2592x1900 WEBP on mobile as well as on desktop?

**Comment by Jonatan-r** [comment]
@felixhaeberle any update on this? 😄

**Comment by psntr** [comment]
@Jonatan-r you can now use kirby default function to output webp in srcset since version 3.6.0. See the official doc [here](https://getkirby.com/docs/guide/templates/resize-images-on-the-fly#image-formats).

**Comment by Jonatan-r** [comment]
@psntr Thanks! 😄 I found out after a while haha... 😅
