### ISSUE TITLE
.htaccess configuration issue

### ISSUE THREAD

**Issue by nwong212** [felixhaeberle/kirby3-webp#4]
Hello,

I'm not sure if I am implementing the apache configuration correctly... I copy and paste directly into the .htaccess, and all images that are being served are .jpg versions instead of the .webp versions. If I understand the configuration correctly, if the browser can load webp images and a webp image with the same name as the .jpg or .png is within the same directory, then the webp is served in place of the .jpg?

If so, maybe the existence of the kirby /media folder that places each image within serialized folders is causing an issue? I'm not really sure how to fix this issue or whether my diagnosis is even correct 🥴

I have tested on both Kirby v3.1.3 and v3.4.0

**Comment by dviate** [comment]
This is actually not a configuration issue, I'll try to explain what's happening when you're requesting an image.
``` 
# Checking for WebP browser support ..
RewriteCond %{HTTP_ACCEPT} image/webp

# .. and if there's a WebP version for the requested image
RewriteCond %{DOCUMENT_ROOT}/$1.webp -f

# Well, then go for it & serve WebP instead
RewriteRule (.+)\.(jpe?g|png)$ $1.webp [T=image/webp,E=accept:1]
```

The first - not commented - line sets the condition "_**if** the browser supports WebP_", the second line sets the condition "_**if** `example.webp` exists_" and the third line is only fired if the previous conditions return `true`; "_let's rewrite `example.jpg`'s replacement `example.webp`, the WebP-version!_"

You can easily verify your browser shows you either the original file or the WebP-version by checking the filesize.
