### ISSUE TITLE
Verification error

### ISSUE THREAD

**Issue by nncrns** [felixhaeberle/kirby3-webp#5]
Hi there,

I have installed your plugin in my local development and just tried uploading a photo to the Panel. It gives me this error (saying that the source of the program can't be verified):

<img width="434" alt="Bildschirmfoto 2020-08-04 um 10 31 04" src="https://user-images.githubusercontent.com/47850358/89272111-f598c380-d63d-11ea-8a17-f958dcaeb5f1.png">

I know how to override this, however it does give me pause to wonder what the source exactly is? Maybe you could clarify?

Would this error (or similar) will occur once the site is on a live server and my clients are uploading?

Thanks for your help!

**Comment by felixhaeberle** [comment]
Hey, thanks for using the plugin!

Unfortunately, your bug report doesn't sound like you use the plugin in the right way, please read the installation instructions in the README.md and follow the instructions there, thanks.

Have a nice day!
