### ISSUE TITLE
'The file could not be uploaded' error

### ISSUE THREAD

**Issue by MichaelPrecel** [felixhaeberle/kirby3-webp#7]
There's an error happening on upload at times where Kirby presents an error message saying 'The file could not be uploaded' and when checking the content folder there is a _.webp.lossy.webp_ version of the file, but not the final .webp version. 

<img width="1373" alt="Screen Shot 2021-04-01 at 2 18 30 pm" src="https://user-images.githubusercontent.com/27719652/113240679-ea935180-92f8-11eb-8a16-a17dd89f586f.png">
<img width="1374" alt="Screen Shot 2021-04-01 at 2 18 39 pm" src="https://user-images.githubusercontent.com/27719652/113240687-ecf5ab80-92f8-11eb-8cc6-ae9173b165ca.png">

Settings as below:
`'kirby3-webp' => [
'quality' => 'auto',
'maxQuality' => 75,
 'defaultQuality' => 80,
'metadata' => 'none',
'encoding' => 'auto'
],`

Possibly the server computing power is being maxed out and the process is being interrupted? Is there anything we can do to prevent this situation?

Would be keen to hear your thoughts! Thanks :)

**Comment by felixhaeberle** [comment]
Can you test with v2 of the plugin which just got released?
If it doesn't work, please reopen this issue.
