### ISSUE TITLE
Server always serves jpg

### ISSUE THREAD

**Issue by dwd0tcom** [felixhaeberle/kirby3-webp#8]
As much as I tried: My apache server always displays the .jpgs, not the created .webp. 
Also the .webp are not located in the media folder which is linked to the kirby content folder.

**Comment by dwd0tcom** [comment]
Oh, I guess this is a duplicate of https://github.com/felixhaeberle/kirby3-webp/issues/6

**Comment by felixhaeberle** [comment]
Yes, this is currently an issue with this plugin and I would be more as happy if someone could jump in and fix it with a PR because unfortunately I don't have time atm. 🙏

**Comment by dwd0tcom** [comment]
I guess we can close this, since it's now supported in kirby.
